### ISSUE TITLE
Hardware sponsoring :-)

### ISSUE THREAD

**Issue by jonashaag** [pheepa/DCUnet#1]
Hi! Just stumbled upon this repo when looking for pretrained DCUnet models. Thanks for uploading a pretrained model.

You say that you have no hardware to train for longer time. Few suggestions:

- Did you know that you can "trick" Colab into not interrupting your training using fake Javascript page interactions? This way you can train for multiple hours without interruption.
- I have Colab Pro, if you're interested you can use it to train for longer time.
- You can use a TPU cluster in Colab to train ~4x as quickly, but I'm not sure how much work it is to implement TPU compatibility given the fact that you do not use TensorFlow.
- I'm interested in sponsoring a training with Large-DCUnet-20 on a GPU for a few hours, provided that you publish the pretrained model here. If you're interested, send me an email at myfirstname at lophus dot org

**Comment by pheepa** [comment]
Hi! I am very glad that you are ready to help me. I did not even think that this topic is so interesting. 
* I didn't know about the colab trick.
* I will contact you later for help. 
* And I plan to translate the notebook, since someone found it useful.
